/** 知识库 / RAG 接入 — 管理端与用户端共用文案（与具体厂商解耦） */
export const knowledgeIntegrationCopy = {
  gatewayRoute: '/admin/model-gateway',
  credentialsRoute: '/admin/model-gateway?tab=knowledge',
  credentialsLink: '网关中心 · 知识向量化',
  credentialsTitle: '知识向量化',
  credentialsSubtitle:
    '配置第三方知识库 API 的 AppId / Secret，用于文档上传、云端解析、向量化与检索。与 Chat 模型密钥统一在网关中心管理。',
  credentialsDrawerHint: '凭证已迁移至网关中心，建议在全屏页签中配置：',
  credentialsLoadError: '无法加载知识库接入配置，请确认后端已启动并完成数据库迁移（0024、0026、0031）。',
  useSavedCredentialsLabel: '使用本页保存的密钥',
  useSavedCredentialsHint: '取消勾选后只读取 .env 环境变量，不使用此处已保存的内容。',
  credentialsApiDocLabel: '接入文档',
  credentialsTemplateLabel: '接入模板',
  credentialsProviderTemplateLabel: '预置模板',
  credentialsProviderTemplatePlaceholder: '选择预置供应商模板',
  credentialsTemplatePlaceholder: '选择第三方知识库模板',
  credentialsDeleteTitle: '删除供应商凭证',
  credentialsDeleteHint:
    '将清除管理端已保存的 AppId / Secret 与测试记录；预置供应商卡片不会移除。.env 环境变量不受影响，删除后若仍显示「环境变量」表示系统正从 .env 读取凭证。',
  credentialsDeletedWithEnv:
    '已清除管理端凭证。当前仍由 .env 提供连接信息，卡片会显示「环境变量」；若要彻底停用请修改 .env。',
  credentialsDeletedDone: '已清除管理端保存的凭证，请重新填写或依赖 .env。',
  knowledgeAddTemplateTitle: '新增供应商',
  knowledgeAddTemplateHint: '从预置模板中选择要接入的云端知识库，添加后可在卡片中配置凭证。',
  knowledgeAddTemplateEmpty: '所有预置模板均已添加，无可新增项。',
  knowledgeInstancesEmpty: '暂无供应商，请点击「新增供应商」从预置模板添加。',
  credentialsTemplateBundledFallback:
    '未能从后端拉取最新模板，已使用内置副本。请确认后端已启动（默认端口 8001）后刷新页面。',
  appIdPlaceholder: '控制台 AppId',
  apiSecretPlaceholder: '控制台 APISecret',

  wikiFilterScoreLabel: '检索相似度阈值',
  wikiFilterScoreHelpTitle: '检索相似度阈值（wikiFilterScore）',
  wikiFilterScoreHelpIntro:
    '讯飞 ChatDoc 在向量检索时，会给每个文档片段打一个相似度分数。只有分数不低于该阈值的片段才会返回，低于阈值的会被丢弃。',
  wikiFilterScoreHelpTuneHigher: '调高（如 0.90）：更严格，结果更少、更精准。',
  wikiFilterScoreHelpTuneLower: '调低（如 0.70）：更宽松，召回更多，但可能混入不太相关的内容。',
  wikiFilterScoreHelpDefault: '默认 0.82 即可；检索结果偏少时可适当调低，噪音太多时可适当调高。',
  wikiFilterScoreHelpScope: '影响 AI 学习室召回、管理端「检索测试」等所有向量检索场景，与 AppId / Secret 无关。',

  sidebarKnowledgeHelper: '全部/单课/单文档 · 入库与检索',
  sidebarCredentialsLabel: '网关 · 知识向量化',
  sidebarCredentialsHelper: 'RAG 接入密钥（网关中心）',

  designModeTitle: '知识库设计模式（未配置凭证）',
  designModeMock: '当前使用前端 Mock 数据，不请求后端与外部知识库 API。适合 UI 走查与答辩排练。',
  designModeOffline:
    '未配置知识库凭证时，PDF 不会入库，检索与分段预览使用内置 Fixture。解析与向量化由云端知识库服务完成。',

  knowledgeBaseSubtitle:
    'PDF / TXT / MD 提交云端知识库解析与向量化；支持检索调试、分段预览与引用验证。',
  cloudPipelineTitle: '云端处理流水线',
  cloudPipelineHint: 'PDF / TXT / MD 的解析、分段与向量化在云端完成；本系统同步文档状态与检索结果。',
  chunkPreviewTitle: '分段预览',
  chunkPreviewHint: '云端分段接口',
  nativeSliceWorkflowTitle: '原生切片 · 分步入库',
  nativeSliceWorkflowHint:
    '上传后云端解析并按 chunkSize 切分，流程停在「已切分」；通过 GET file/chunks 全量拉取原生分片入库，再手动向量化。',
  nativeSliceDocUrl: 'https://chatdoc.xfyun.cn/docs#/',
  nativeSliceDocLabel: '讯飞 ChatDoc 开放文档',
  nativeSlicePullLabel: '拉取并入库',
  nativeSlicePullHint: 'GET /openapi/v1/file/chunks?fileId=… 覆盖写入本地 document_chunks',
  nativeSliceResplitLabel: '自定义重切',
  nativeSliceResplitHint:
    '推荐「官方默认重切」（isSplitDefault=true）；高级面板可填 chunkSize/minChunkSize 自定义重切',
  nativeSliceTextbookPresetHint:
    '默认不传 extend，由讯飞内置 wiki 切分；自定义见官方文档 chunkSize=2000、minChunkSize=200。',
  nativeSliceEmbedLabel: '提交向量化',
  nativeSliceEmbedHint: 'POST /file/embedding，将已选或全文分片写入云端向量索引',
  nativeSliceTableTitle: '本地原生切片库',
  nativeSliceReconcileOk: '云端段数与本地一致',
  nativeSliceReconcileMismatch: '云端段数与本地不一致，请重新拉取或重切',
  nativeSliceEmpty: '尚未入库。文档处于「已切分」后点击「拉取并入库」，或等待后台自动入库。',
  nativeSliceAutoSyncHint: '检测到已切分，正在自动拉取原生分片入库…',
  nativeSliceAutoSyncDone: '已自动入库，可在下方表格查看与编辑。',
  nativeSlicePdfTitle: 'PDF 预览',
  nativeSlicePdfHint: '点击页码或切片可双向定位；左侧高亮当前页分片。',
  nativeSliceRevisionTitle: '版本管理',
  nativeSliceRevisionHint: '每次自动入库、重切、手动保存均生成快照，可回滚至自动切片基线。',
  nativeSliceRollbackBaseline: '回滚到自动切片',
  nativeSliceRollbackConfirm: '将用所选版本覆盖当前本地切片，未向量化的编辑会丢失。确认回滚？',
  nativeSliceTraceTitle: '溯源能力说明',
  managedDocBadge: '云端托管',
  managedDocIdPrefix: '云端',
  drawerTitle: '文档分段',
  unboundDocHint: '该文档未绑定云端知识库，请重新上传 PDF / TXT / MD 完成解析与向量化。',
  retrievalModeHint: '向量模式：语义召回。',
  hitTestHint: '对接管理端检索 API，验收 topN 召回片段、相似度与检索模式。',
  citationEmpty: '本轮暂无引用。提问后会展示知识库引用段落、页码和相似度。',
  gatewaySubtitle:
    '统一管理 Chat 对话模型与课程知识向量化（云端 RAG）密钥；在此切换配置，无需分散到知识大本营。',
  gatewayKnowledgeHint: '切换至「知识向量化」页签配置云端知识库 AppId / Secret；流水线参数请在文档上传、萃取、检索测试等操作中填写。',
  providerCredentialHint:
    '连接参数已按预置模板填好，只需填写 API Key；填写完整后可先测试连接，再保存配置。',
  chatEditorSaveSuccess: '配置已保存并已发布热加载。可在此面板点击「测试连接」验证连通性。',
  chatEditorTroubleshootHint: '排障时可先保存配置，再在本面板点击「测试连接」查看接口返回。',
  chatCustomAddHint: '填写 OpenAI 兼容端点与模型名称；预置模板可一键带入官方参数。',
  chatCustomApiKeyHint: '只需填写 API Key，Base URL 与模型名称按你的服务端点配置。',
  chatCustomBaseUrlHint: '填写兼容 OpenAI Chat Completions 格式的服务端点地址（通常以 /v1 结尾）。',
  chatCustomModelHint: '指定调用的模型 ID，保存后网关将使用该模型发起对话请求。',
  knowledgeEditorHint: '接入模板已按预置填好，只需填写控制台凭证；切换模板可配置不同云端知识库。',
  knowledgeEditorAddHint: '选择预置厂商模板，或选「通用云端 RAG」填写 API 地址与密钥。',
  knowledgeEditorPickTemplateHint: '请从上方「预置模板」下拉框选择要接入的云端知识库，或选择「通用云端 RAG」自定义接入。',
  knowledgeCustomTemplatePlaceholder: '通用云端 RAG（自定义接入）',
  knowledgeGenericBaseUrlHint: '填写知识库/检索服务的 HTTP 根地址（OpenAI 兼容或厂商 REST 文档中的 Base URL）。',
  knowledgeGenericApiKeyHint: '填写控制台颁发的 API Key 或 Bearer Token，保存后加密存储。',
  knowledgeGenericKbIdHint: '部分平台需填写 Dataset / Knowledge Base / Collection ID，无则留空。',
  knowledgeEditorCredentialHint: 'AppId / Secret 等字段请从厂商控制台复制；填写完整后可先测试连接，再保存配置。',
  knowledgeAddSaveSuccess: '供应商已添加，凭证已保存。',
  knowledgeEditorSaveSuccess: '凭证已保存。可在此面板点击「测试连接」验证连通性。',
  knowledgeEditorTestFailedHint: '连接测试未通过，请查看本面板下方的测试结果。',
  knowledgeEditorTroubleshootHint: '排障时可先保存配置，再在本面板点击「测试连接」查看接口返回。',
  chatdocQuotaTitle: '讯飞 ChatDoc 套餐余量（本地统计）',
  chatdocQuotaCardTitle: '套餐余量（本地）',
  chatdocQuotaCardUnset: '未配置上限，点击「编辑」填写讯飞控制台采购量',
  chatdocQuotaEditorTitle: '讯飞套餐余量',
  chatdocQuotaLoadError:
    '无法加载讯飞套餐余量。若接口 503，请在 backend 目录执行：alembic upgrade head（迁移 0028_chatdoc_vendor_quota）。',
  chatdocQuotaHint:
    '上限请按讯飞开放平台控制台采购量填写；已用量由本系统按官方扣量规则累计（非讯飞实时接口）。可与控制台定期「同步已用量」校准。',
  chatdocQuotaConfigTitle: '配置套餐上限与校准已用量',
  chatdocQuotaSyncHint: '若曾在控制台外直接调用讯飞 API，或更换 AppId 后，可在此将已用量改为与控制台一致。',
  chatdocQuotaSaveSuccess: '套餐上限已保存，上方卡片已更新剩余额度。',
  chatdocQuotaSyncSuccess: '已用量已同步，上方统计卡片已刷新。',
  chatdocQuotaUploadRule: '扣量 = file/upload 返回的 quantity（页）；PDF/DOC 按自然页计费。',
  chatdocQuotaDocQaRule:
    '扣量 = 每次 §3.3 WebSocket 文档问答成功调用 +1 次；智课检索走 vector/search，不计入此项。',
  chatdocQuotaExtractRule: '扣量 = 每次文件萃取任务成功调用 +1 次。',
  monitoringSubtitle:
    '云原生运维：成本额度、Webhook/补偿轮询、检索时延与 Guardrail 拒答；本地队列仅覆盖资源生成。',
  monitoringIngestionTitle: '云端知识资产',
  monitoringIngestionEmpty: '暂无云端托管文档',
  monitoringIngestionHint: '知识库向量化与分段由云端服务完成；Chat 与向量化密钥均在网关中心配置。',
  stageReadySearchable: '云端可向量化检索',
  stageAwaitingActivation: '待授权入库',
  stageVectorizing: '云端向量化中',
  stageRegisterSync: '云端登记与同步',
  batchEmbedLabel: '批量向量化激活',
  batchEmbedHint: '仅对已切分、待向量化的文档生效',
  batchEmbedDialogHint: '选择讯飞接入实例后，对所选文档提交向量化激活。',
  uploadDialogHint: '选好接入方式，配置参数后提交。',
  uploadLimitFallbackHint: '支持 PDF / MD / TXT；单文件大小以后端配置为准。',
  uploadDuplicateWarning: '检测到与本课程已有文档内容相同，已登记为新记录并继续云端处理。',
  uploadDuplicateBlocked: '本课程已有相同内容的文档，无需重复上传。',
  uploadDuplicateFilenameWarning: '本课程已有同名文档，默认不会再次提交；勾选下方「强制重新上传」后可继续。',
  uploadDuplicateFilenameBlocked: '本课程已有同名文档「{name}」，请勾选「强制重新上传」或先删除/重命名后再传。',
  ingestionTaskExistingDocHint: '以下为本次操作触发的入库任务（不含课程内其他历史处理中文档）。',
  uploadForceReuploadLabel: '强制重新上传（忽略重复检测）',
  uploadForceReuploadHint: '仅在确需重新走云端解析/向量化时勾选；默认会拦截相同内容的重复文件。',
  documentDuplicateBadge: '重复内容',
  documentFailedHintPrefix: '失败原因：',
  uploadStageTitle: '上传参数',
  uploadStageHint: '控制文档如何解析、切分；开启分步模式后，切完需手动点「批量向量化激活」。',
  extractLabel: '文档萃取',
  extractHint: '对已向量化的文档提交 QA 萃取任务',
  extractDialogTitle: '提交文档萃取',
  extractDialogHint: '选择接入方式并填写萃取参数。',
  extractStageTitle: '萃取参数',
  extractStageHint: '控制如何从文档里抽取问答对。',
  retrievalStageTitle: '检索参数',
  retrievalStageHint: '控制检索返回多少条、相似度门槛等。',
  uploadStepByStepMessage:
    '文档已提交云端解析与切分；切分完成后请勾选文档并点击「批量向量化激活」。',
  stageLegacyReupload: '历史本地记录，请重新上传由云端知识库托管',
  cloudFileStatusTitle: '云端 fileStatus',
  ingestionCloudPipelineInfo: 'PDF / TXT / MD 提交云端知识库：解析、分段、向量化在云端完成。',
  cloudCredentialsCheck: '云端处理失败，请检查知识库凭证或重新上传。',
  hitTestConceptFilter: '将按知识点绑定文档过滤 fileIds',
  chunkLoadError: '无法加载云端分段，请确认密钥与文档已向量化。',
  hitTestVerifyHint:
    '配置凭证前可在「检索测试」Tab 使用 Fixture 数据；配置后可验证真实向量检索召回效果。',
  documentSubmitted: '已提交云端知识库解析与向量化。',
  submitGuardOfflineTitle: '网络不可用',
  submitGuardOfflineBody: '当前处于离线状态，请检查网络连接后重试。',
  submitGuardBackendTitle: '无法连接后端',
  submitGuardBackendBody:
    '请先启动后端服务（默认 http://localhost:8001），并确认前端代理或 VITE_API_BASE_URL 配置正确。',
  submitGuardChatdocTitle: 'ChatDoc 凭证未就绪',
  submitGuardChatdocBody:
    '请先在「网关中心 · 知识向量化」配置 AppId / Secret 并通过连接测试，再提交文档或向量化任务。',
  submitGuardCourseTitle: '未选择课程',
  submitGuardCourseBody: '请先在顶栏选择要上传文档的目标课程。',
  submitGuardLoadingTitle: '正在检查接入配置',
  submitGuardLoadingBody: '请稍候，正在读取 ChatDoc 凭证状态…',
  submitGuardEmbedNotReadyTitle: '暂不可向量化',
  submitGuardEmbedNotReadyBody:
    '文档需处于「已切分 / 待授权入库」状态。请等待云端切分完成并拉取原生分片后再提交向量化。',
  submitSuccessUpload: '文档已提交云端处理。',
  submitSuccessEmbed: '已向 {accepted} 份文档提交向量化。',
  submitSuccessEmbedPartial: '已向 {accepted} 份文档提交向量化，{rejected} 份未满足条件。',
  submitSuccessEmbedAllRejected: '所选文档均无法向量化，请确认状态为「待授权入库」。',
  submitSuccessExtract: '已向 {accepted} 份文档提交萃取任务。',
  submitSuccessExtractPartial: '已提交 {accepted} 份萃取，{rejected} 份跳过。',
  submitSuccessExtractAllRejected: '所选文档均无法提交萃取，请确认已向量化。',
  submitSuccessSync: '原生分片已拉取并入库。',
  submitSuccessResplit: '已提交自定义重切，正在同步本地分片…',
  submitSuccessEdit: '分片已保存到本地库，确认后可提交向量化。',
  submitSuccessEmbedSingle: '已向量化任务已提交，请等待云端处理完成。',
  mockManagedPdf: 'Mock 云端 PDF',
  workspaceKnowledgeSubtitle: '文档入库、分段预览与检索调试',
  retrieveQueued: '知识库检索未触发',
  retrieveWaiting: '等待知识库检索',
  retrieveRunning: '知识库召回、画像偏好和章节权重正在汇合',
  retrieveBusy: '正在检索知识库并核验引用来源…',
} as const;
